name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: nest-service

      - name: Generate Prisma Client
        run: npm run prisma:generate
        working-directory: nest-service

      - name: Lint
        run: npm run lint
        working-directory: nest-service

      - name: Build
        run: npm run build
        working-directory: nest-service

      - name: Test
        run: npm test -- --runInBand
        working-directory: nest-service
